### ISSUE TITLE
invalid conversion from ‘const char*’ to ‘char*’

### ISSUE THREAD

**Issue by marcvs** [Homegear/libhomegear-python#1]
Not sure, why this error pops up, suddenly, but well here it is:

pip3 install homegear  fails on my debian/testing, as well as on my rasbbian buster with:

    homegear.cpp:317:47: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]

**Comment by marcvs** [comment]
I reproduced this via `pip install`, as well as via the `setup.py install` commands.

fixed this in my fork at https://github.com/marcvs/libhomegear-python.

**Comment by marcvs** [comment]
Just checked. It appears that this issue does not occur with python 3.5, but with 3.7.

**Comment by hfedcba** [comment]
Thanks! I changed the two `char*` to `const char*`. Hopefully it works now.
