### ISSUE TITLE
ImportError: undefined symbol __atomic_load_8

### ISSUE THREAD

**Issue by marcvs** [Homegear/libhomegear-python#2]
I've upgraded the debian/buster packages. Since then the python homegear package stopped working. The error is this one:
```
echo from homegear import Homegear | python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/libhomegear-ipc.so.1: undefined symbol: __atomic_load_8
```
In my quest to fix it, I tried:
- reinstalling the debian packages
- The manual install of libhomegear-ipc from the readme:
```
        git clone https://github.com/Homegear/libhomegear-ipc
        cd libhomegear-ipc
        sudo ./makeRelease.sh
```
- Recompiling and installing python3-homegear:
```
        sudo python3 setup.py install
```

Nothing changes the error message.

Any help appreciated.

**Comment by hfedcba** [comment]
Did you try compiling the dev version?

`git checkout dev`

The error might already be fixed.

**Comment by hfedcba** [comment]
To check, you can install the nightly packages in Buster.

**Comment by marcvs** [comment]
Thanks for the quick response!

I tried the dev version of first homegear-ipc, and then also python3-homegear. Both without success. I'll take a look at the nightlies in Buster later this week.

**Comment by marcvs** [comment]
Checked nightly, but this does not seem to help.

**Comment by marcvs** [comment]
I think the problem I have was introducted with 0.7.39 => 0.7.40.
I'm now building for stretch and the latest version, since I couldn't find information on how to build for buster and a given version.
Could you point me to some documentation?

**Comment by hfedcba** [comment]
Could you check if it works with the current development version of `libhomegear-ipc`? The library was not linked against `libatomic`. In the current development version that is fixed.

**Comment by marcvs** [comment]
It took me a while to dig through the building process... I've used the debian-buster-armhf docker container to build a .deb for libhomegear-ipc from it's dev branch (into libhomegear-ipc_0.1.2-38_armhf.deb). I've followed the instructions found in `CreateDebianPackage.sh`. This changes the error message to:
```
echo from homegear import Homegear | python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python3/dist-packages/homegear.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: _ZN3Ipc10IIpcClient6invokeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrISt6vectorIS9_INS_8VariableEESaISC_EEE
```

Any Idea?

**Comment by marcvs** [comment]
No change, if I compile the python3-homegear libs in the same way.

**Comment by hfedcba** [comment]
You recompiled `libhomegear-ipc` and `python3-homegear` (both the updated dev version)?

**Comment by marcvs** [comment]
Yep

**Comment by marcvs** [comment]
I'll try to go for 0.7.39 to see if that works.

**Comment by marcvs** [comment]
Ok; I managed to mess things up in weird ways:
The self-compiled libhomegear-ipc/master (0.1.2-30) brings me into a state that works for the python3-homegear interface. However, homegear -r gives me:
```
12/28/19 18:18:39.553 Warning: Setting not found: reloadRolesOnStartup 
12/28/19 18:18:39.554 Warning: Setting not found: reloadRolesOnStartup 
terminate called without an active exception
Aborted
```
There's nothing in the logs
If I install the shipped one (same version 0.1.2-30) it's the other way round: Python gives the undefines symbol atomic_load_8, but homegear -r works.

I'll go recompile from "master" once more and install all of them.

**Comment by hfedcba** [comment]
On which architecture does the error occur? amd64?

**Comment by marcvs** [comment]
armhf.

M.

On 01/02/20 05:48, Sathya Laufer wrote:
> On which architecture does the error occur? amd64?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Homegear/python3-homegear/issues/2#issuecomment-570212099

-- 
Marcus.

**Comment by hfedcba** [comment]
I don't have a Debian armhf system at the moment, but it works in the Docker container. When compiling manually, the module is placed in `/usr/local/lib`. Could you execute

    rm /usr/lib/python3/dist-packages/homegear*
    rm /usr/local/lib/python3.7/dist-packages/homegear*

and reinstall or recompile the module?

**Comment by marcvs** [comment]
ok; I got my system pretty messy. I'm rebuilding Stable and Nightly with the provided scripts and will report back.

**Comment by marcvs** [comment]
I apt-get removed the python3-homegear package and verified that the two folders you mentioned, and installed the self compiled one (CreateDebianPackageStable.sh). This is the error:
```
  ImportError: /usr/lib/python3/dist-packages/homegear.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: _ZN3Ipc10IIpcClient5startEj
```
The stock package works (with self-compiled libhomegear-ipc/master (0.1.2-30))

The Nightly package shows the same error.
M.

**Comment by hfedcba** [comment]
With `0.1.2-30` it won't work. `0.1.2-38` is the current version in the master branch. With that version, it should work. With `0.1.2-30` it can't.

Please use either the `dev` branch on both (= nightly) or the `master` branch on both (= stable), but don't mix them.

**Comment by marcvs** [comment]
I had a busy week, sorry for the delay.

I just upgraded via debian to homegear 0.7.44 and libhomegear-ipc-0.1.2-38.

Still i'm getting an undefined symbol error. 
```
ImportError: /usr/lib/python3/dist-packages/homegear.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: _ZN3Ipc10IIpcClient6invokeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrISt6vectorIS9_INS_8VariableEESaISC_EEE
```

This does not change, if I install the packages built last weekend (0.7.43 + 0.1.2-38 + 1.0.14-1))

**Comment by hfedcba** [comment]
I finally might've found the error. It should be fixed in the current nightly.

**Comment by marcvs** [comment]
Yes!  I can confirm it working!

Thanks a lot!!

Will the fix go to buster packages, or only to the nightlies?

**Comment by hfedcba** [comment]
The fix should already be in Testing and Stable.

**Comment by marcvs** [comment]
Yep, confirmed.
Thanks again!!
